apiVersion: v1
kind: Pod
metadata:
  name: slurm-controller
  labels:
    app: slurm-controller
spec:
  hostname: slurm-controller
  containers:
    - name: slurm-controller
      image: kedar-slurm:2.0
      command: ["/bin/bash"]
      args:
        - "-c"
        - |
          cp /mnt/munge/munge.key /etc/munge/munge.key && \
          chown munge:munge /etc/munge/munge.key && \
          chmod 400 /etc/munge/munge.key && \
          service munge start && \
          slurmctld -D
      volumeMounts:
        - name: slurm-config
          mountPath: /etc/slurm/slurm.conf
          subPath: slurm.conf
        - name: munge-secret
          mountPath: /mnt/munge
  volumes:
    - name: slurm-config
      configMap:
        name: slurm-config
    - name: munge-secret
      secret:
        secretName: slurm-munge
